# Generated by Django 5.0.3 on 2024-03-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenciesmodel',
            name='rates',
            field=models.ManyToManyField(blank=True, to='api.currencyratesmodel'),
        ),
    ]
