# Generated by Django 5.0.3 on 2024-03-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_currenciesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyratesmodel',
            name='base_currency',
            field=models.CharField(max_length=3, verbose_name='Moeda base'),
        ),
        migrations.AlterField(
            model_name='currencyratesmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='currencyratesmodel',
            name='rate',
            field=models.FloatField(verbose_name='Taxa de câmbio'),
        ),
        migrations.AlterField(
            model_name='currencyratesmodel',
            name='to_currency',
            field=models.CharField(max_length=3, verbose_name='Moeda destino'),
        ),
    ]
